"""FDA/EMA regulatory dossier formatting.

Generates evidence documents formatted for regulatory submission:
- FDA eCTD Module 2.5 (Clinical Overview)
- FDA eCTD Module 2.7.3 (Summary of Clinical Efficacy)
- FDA eCTD Module 2.7.4 (Summary of Clinical Safety)
- FDA Plausible Mechanism Framework (February 2026)
- PRISMA 2020 flow diagram placeholder

eCTD format reference:
  https://www.fda.gov/drugs/electronic-regulatory-submission-and-review/electronic-common-technical-document-ectd
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from evidence_ai.summarize.models import EvidenceReview

logger = logging.getLogger(__name__)


class RegulatoryFormatter:
    """Format evidence reviews into regulatory submission documents.

    Generates text and document files formatted for FDA eCTD submission
    or the Plausible Mechanism Framework pathway.
    """

    def generate_module_25(self, review: "EvidenceReview") -> str:
        """Generate FDA eCTD Module 2.5 (Clinical Overview) text.

        Module 2.5 is the Clinical Overview — a critical analysis and summary
        of the clinical information submitted to the FDA.

        Args:
            review: The completed evidence review.

        Returns:
            Formatted text suitable for Module 2.5.
        """
        lines = [
            "2.5 CLINICAL OVERVIEW",
            "=" * 60,
            "",
            "2.5.1 Product Development Rationale",
            "-" * 40,
            f"This section provides a summary of the clinical evidence supporting "
            f"the efficacy and safety profile of the product in the context of: "
            f"{review.question}",
            "",
            "2.5.2 Overview of Biopharmaceutics",
            "-" * 40,
            "(Populated from preclinical and Phase I data — not synthesized by EvidenceAI)",
            "",
            "2.5.3 Overview of Clinical Pharmacology",
            "-" * 40,
            "(Populated from clinical pharmacology data — not synthesized by EvidenceAI)",
            "",
            "2.5.4 Overview of Efficacy",
            "-" * 40,
            f"Evidence Synthesis:",
            f"  Level of Evidence: {review.level_of_evidence:.2f} ({review.loe_label})",
            f"  Effect Direction: {review.effect_direction.value}",
            f"  Studies Included: {review.papers_included}",
            f"  (RCTs: {review.triangulation.rct_count if review.triangulation else 'N/A'}, "
            f"Meta-analyses: {review.triangulation.meta_count if review.triangulation else 'N/A'})",
            "",
            "Evidence Summary:",
            review.summary,
            "",
            "Key Findings:",
        ]
        for finding in review.key_findings:
            lines.append(f"  • {finding}")

        lines += [
            "",
            "2.5.5 Overview of Safety",
            "-" * 40,
            "(Populated from integrated safety analysis — see Module 2.7.4)",
            "",
            "2.5.6 Benefit-Risk Conclusions",
            "-" * 40,
            f"Based on the systematic review of {review.papers_screened} publications "
            f"(including {review.papers_included} eligible studies), the evidence "
            f"demonstrates {review.loe_label} support for the claimed therapeutic effect.",
            "",
            f"Generated by EvidenceAI v0.1.0 | Review ID: {review.review_id}",
            f"Generated at: {review.generated_at.isoformat()}",
        ]

        return "\n".join(lines)

    def generate_module_273(self, review: "EvidenceReview") -> str:
        """Generate FDA eCTD Module 2.7.3 (Summary of Clinical Efficacy) text.

        Args:
            review: The completed evidence review.

        Returns:
            Formatted text suitable for Module 2.7.3.
        """
        lines = [
            "2.7.3 SUMMARY OF CLINICAL EFFICACY",
            "=" * 60,
            "",
            "2.7.3.1 Background and Overview of Clinical Efficacy",
            "-" * 40,
            review.summary,
            "",
            "2.7.3.2 Summary of Results of Individual Studies",
            "-" * 40,
        ]

        if review.evidence_table:
            lines.append(
                f"{'Authors':<30} {'Year':<6} {'Design':<10} {'N':<8} "
                f"{'Effect':<20} {'Outcome'}"
            )
            lines.append("-" * 90)
            for row in review.evidence_table[:30]:
                lines.append(
                    f"{row.authors[:28]:<30} {str(row.year or 'N/A'):<6} "
                    f"{row.study_design:<10} {str(row.sample_size or 'N/A'):<8} "
                    f"{row.effect_estimate:<20} {row.primary_outcome[:40]}"
                )
        else:
            lines.append("(No individual studies available in evidence table)")

        lines += [
            "",
            "2.7.3.3 Comparison of Results of Individual Studies",
            "-" * 40,
            f"Convergence of Evidence Analysis:",
            f"  p(excitatory) = {review.coe_scores.p_excitatory:.4f}",
            f"  p(no_change)  = {review.coe_scores.p_no_change:.4f}",
            f"  p(inhibitory) = {review.coe_scores.p_inhibitory:.4f}",
            f"  Level of Evidence (LoE) = {review.level_of_evidence:.4f}",
            "",
            f"Generated by EvidenceAI v0.1.0 | Review ID: {review.review_id}",
        ]
        return "\n".join(lines)

    def generate_module_274(self, review: "EvidenceReview") -> str:
        """Generate FDA eCTD Module 2.7.4 (Summary of Clinical Safety) text.

        Args:
            review: The completed evidence review.

        Returns:
            Formatted text suitable for Module 2.7.4.
        """
        lines = [
            "2.7.4 SUMMARY OF CLINICAL SAFETY",
            "=" * 60,
            "",
            "2.7.4.1 Exposure to the Drug",
            "-" * 40,
            f"Total patient exposure across included studies: "
            f"{sum(r.sample_size or 0 for r in review.evidence_table)} patient-observations",
            "",
            "2.7.4.2 Adverse Events",
            "-" * 40,
            "(Adverse event analysis requires structured safety data from individual "
            "clinical study reports — not extracted from abstracts by EvidenceAI v0.1.0. "
            "This section should be completed manually using CSR-level data.)",
            "",
            "NOTE: EvidenceAI v0.1.0 synthesizes efficacy evidence from literature. "
            "Integrated safety analysis (ISS) requires access to patient-level data "
            "or detailed CSRs, which are not available from PubMed abstracts.",
            "",
            f"Generated by EvidenceAI v0.1.0 | Review ID: {review.review_id}",
        ]
        return "\n".join(lines)

    def generate_plausible_mechanism(self, review: "EvidenceReview") -> str:
        """Generate evidence for FDA's Plausible Mechanism Framework (Feb 2026).

        The Plausible Mechanism Framework (launched February 2026) allows
        approval of individualized therapies based on mechanistic evidence
        rather than large randomized trials.

        Required elements:
        1. Identifying the disease-causing abnormality
        2. Therapy targets the root cause or proximate biological pathway
        3. Well-characterized natural history data
        4. Successful target drugging (prior evidence)
        5. Improvement in clinical outcomes

        Reference:
          https://www.fda.gov/news-events/press-announcements/
          fda-launches-framework-accelerating-development-individualized-therapies-ultra-rare-diseases

        Args:
            review: The completed evidence review.

        Returns:
            Formatted text for the Plausible Mechanism Framework evidence package.
        """
        lines = [
            "FDA PLAUSIBLE MECHANISM FRAMEWORK — EVIDENCE PACKAGE",
            "=" * 60,
            "Framework launched: February 2026",
            "Reference: FDA news release, February 2026",
            "",
            review.summary,
            "",
            "ELEMENT 1: DISEASE-CAUSING ABNORMALITY",
            "-" * 40,
            f"[Complete with disease-specific pathomechanism data for {review.question}]",
            "",
            "ELEMENT 2: THERAPY TARGETS THE ROOT CAUSE",
            "-" * 40,
            f"Evidence base: {review.papers_included} studies demonstrate "
            f"{review.effect_direction.value} effect (LoE={review.level_of_evidence:.2f}).",
            "",
            "ELEMENT 3: NATURAL HISTORY DATA",
            "-" * 40,
            "[Complete with natural history data from ClinicalTrials.gov and registry studies]",
            "",
            "ELEMENT 4: SUCCESSFUL TARGET DRUGGING",
            "-" * 40,
            f"Prior evidence from {review.triangulation.rct_count if review.triangulation else 0} "
            f"RCTs and {review.triangulation.meta_count if review.triangulation else 0} "
            f"meta-analyses demonstrates target engagement.",
            "",
            "ELEMENT 5: CLINICAL OUTCOME IMPROVEMENT",
            "-" * 40,
            review.summary,
            "",
            "KEY FINDINGS:",
        ]
        for finding in review.key_findings:
            lines.append(f"  • {finding}")

        lines += [
            "",
            f"Generated by EvidenceAI v0.1.0 | Review ID: {review.review_id}",
            f"EvidenceAI is designed to support the Plausible Mechanism Framework pathway.",
        ]
        return "\n".join(lines)

    def write_module_25(self, review: "EvidenceReview", output_dir: Path) -> Path:
        """Write Module 2.5 to a text file."""
        text = self.generate_module_25(review)
        path = output_dir / f"module_2.5_clinical_overview_{review.review_id}.txt"
        path.write_text(text, encoding="utf-8")
        logger.info("Wrote Module 2.5 to %s", path)
        return path

    def write_module_273(self, review: "EvidenceReview", output_dir: Path) -> Path:
        """Write Module 2.7.3 to a text file."""
        text = self.generate_module_273(review)
        path = output_dir / f"module_2.7.3_clinical_efficacy_{review.review_id}.txt"
        path.write_text(text, encoding="utf-8")
        logger.info("Wrote Module 2.7.3 to %s", path)
        return path

    def write_module_274(self, review: "EvidenceReview", output_dir: Path) -> Path:
        """Write Module 2.7.4 to a text file."""
        text = self.generate_module_274(review)
        path = output_dir / f"module_2.7.4_clinical_safety_{review.review_id}.txt"
        path.write_text(text, encoding="utf-8")
        logger.info("Wrote Module 2.7.4 to %s", path)
        return path
