"""Pydantic models for synthetic trial data augmentation."""

from __future__ import annotations

from pydantic import BaseModel, Field


class SyntheticEvent(BaseModel):
    """A single synthetic clinical trial event."""

    event_type: str = Field(description="Event type (adverse event, outcome, lab value, etc.)")
    timestamp: float = Field(description="Relative time from enrollment (days)")
    value: float | None = Field(default=None, description="Numeric value (if applicable)")
    label: int = Field(default=0, description="Outcome label (0=control, 1=treatment)")


class SyntheticPatient(BaseModel):
    """A single synthetic patient's event sequence."""

    patient_id: str
    events: list[SyntheticEvent] = Field(default_factory=list)
    arm: str = Field(default="treatment", description="Treatment arm")
    total_follow_up_days: float | None = None

    @property
    def event_count(self) -> int:
        return len(self.events)


class AugmentationResult(BaseModel):
    """Result of synthetic trial data augmentation."""

    original_patient_count: int = Field(description="Number of real patients augmented from")
    synthetic_patient_count: int = Field(description="Number of synthetic patients generated")
    var_multiplier: float = Field(
        default=1.0,
        description=(
            "Privacy knob: 0.1 = high fidelity to original data, "
            "4.0 = high privacy / more variation"
        ),
    )
    patients: list[SyntheticPatient] = Field(default_factory=list)
    generation_method: str = Field(default="TrialSynth-VAE-Hawkes")
    warning: str = Field(
        default=(
            "Synthetic data generated by TrialSynth is not differentially private. "
            "Do not use as a substitute for real patient data in regulatory submissions "
            "without additional privacy validation."
        )
    )
